# Generated by Django 5.0.3 on 2024-11-27 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mudda", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mudda",
            old_name="user_name",
            new_name="userID",
        ),
    ]
