# Generated by Django 5.1.3 on 2024-11-29 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mudda", "0003_mudda_likes_count_searchquery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mudda",
            name="likes_count",
            field=models.ManyToManyField(
                blank=True, related_name="liked_muddas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
